version: 2.0

jobs:

  smoke:
    docker:
        - image: circleci/node:8
    environment:
        NPM_CONFIG_PREFIX: ~/.npm-global

    steps:
        # Prepare working env

        - run:
            name: install npm 6.4.0
            command: sudo npm -g install npm@6.4.0

        - run:
            name: Clone helix-cli
            run: git clone https://github.com/adobe/helix-cli.git

        - run:
            name: Install Git Dependency Maker tool
            command: npm install
            working_directory: helix-cli/scripts/gdm

        - run:
            name: Install using git branches (master or specified)
            command: env GDM_MODULE_BRANCHES=$GDM_MODULE_BRANCHES npm run gdm
            working_directory: helix-cli

        - run:
            name: Clone project-helix.io
            command: git clone https://github.com/adobe/project-helix.io.git

        - run:
            name: Install project-helix.io
            command: npm install
            working_directory: project-helix.io
        
        # run TESTS!
        - run:
            name: prepare test git user
            command: git config --global user.email "you@example.com" && git config --global user.name "CircleCi Build"

        - run:
            name: Debug message on which branches are being used
            command: |
                echo "Branch received as parameter: ${GDM_MODULE_BRANCHES}"

        # run smoke tests
        - run:
            name: Running Smoke Tests
            command: env HLX_SMOKE_EXEC='node ../helix-cli/index.js --log-level warn' npx mocha  --exit test/smoke/*
            working_directory: project-helix.io
            when: always

workflows:
  version: 2
  smoke:
    jobs:
    - smoke
