version: 2.0

jobs:
  build:
    docker:
        # workaround: circleci/node:8 changed and led to 'Error: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory'
        # fix the image to the last known to work build of circleci/node:8 
        # see https://github.com/adobe/helix-cli/issues/353
        - image: circleci/node@sha256:09e1035e50a7574fa1786df406559b4a10362fa62ee552ccb49df89e03249c79
    environment:
        NPM_CONFIG_PREFIX: ~/.npm-global

    steps:
        # Prepare working env
        - checkout
        - run:
            name: Install npm 6.4.0
            command: sudo npm -g install npm@6.4.0

        - run:
            name: Prepare test git user
            command: git config --global user.email "you@example.com" && git config --global user.name "CircleCi Build"

        - run:
            name: Install Git Dependency Maker tool
            command: npm install
            working_directory: scripts/gdm

        # Prepare helix-cli to run the smoke tests
        - run:
            name: Clone helix-cli
            command: git clone https://github.com/adobe/helix-cli.git
        
        - run:
            name: Debug message - branches being used in helix-cli
            command: |
                echo -n "Branch received as parameter: " && [[ ! -z "${GDM_MODULE_BRANCHES}" ]] && echo "${GDM_MODULE_BRANCHES}" || echo "All master"

        - run:
            name: Install using git branches (master or specified)
            command: env GDM_MODULE_BRANCHES=$GDM_MODULE_BRANCHES node ../scripts/gdm/index.js
            working_directory: helix-cli

        # Checkout project-helix.io
        - run:
            name: Clone project-helix.io
            command: git clone https://github.com/adobe/project-helix.io.git

        - run:
            name: Install project-helix.io
            command: npm install
            working_directory: project-helix.io

        # Run the smoke tests
        - run:
            name: Run Smoke Tests on project-helix.io
            command: env HLX_SMOKE_EXEC='node ../helix-cli/index.js --log-level warn' npx mocha  --exit test/smoke/*
            working_directory: project-helix.io

workflows:
  version: 2
  build:
    jobs:
    - build
